### < 3500
GET http://localhost:8080/calculate/1000

# response
#{
#  "wage": 1000.0,
#  "wagemore": 0.0,
#  "cess": 0.0,
#  "preminus": 0.0,
#  "wageminus": 0.0,
#  "actualwage": 1000.0
#}


### 9000 ~ 35000
GET http://localhost:8080/calculate/10000

# response
#{
#  "wage": 10000.0,
#  "wagemore": 6500.0,
#  "cess": 0.2,
#  "preminus": 555.0,
#  "wageminus": 745.0,
#  "actualwage": 9255.0
#}

