###
POST http://localhost:8080/rule/insuranceInfoCheck
Content-Type: application/json

{
  "param1": "PICC",
  "param4": "上海",
  "param5": "101"
}

### response
#{
#  "msg": "准入失败",
#  "detail": [
#    "销售区域不支持", // 销售区域只能为北京和天津
#    "投保人年龄不支持" // 年龄必须是 0 - 17 岁
#  ],
#  "checkResult": false
#}

