package rules.book;
import com.corning.drools.entity.Order;

dialect  "mvel"

//[0, 100) 没有优惠
rule "bookDiscount_1"
    when
        $order:Order(originalPrice < 100)
    then
        $order.setRealPrice($order.getOriginalPrice());
        System.out.printf("bookDiscount_1, %s%n", $order);
end

//[100, 200)，优惠20
rule "bookDiscount_2"
    when
        $order:Order(originalPrice >= 100 && originalPrice < 200)
    then
        $order.setRealPrice($order.getOriginalPrice() - 20);
        System.out.printf("bookDiscount_2, %s%n", $order);
end

//[200, 300)，优惠50
rule "bookDiscount_3"
    when
        $order:Order(originalPrice >= 200 && originalPrice < 300)
    then
        $order.setRealPrice($order.getOriginalPrice() - 50);
        System.out.printf("bookDiscount_3, %s%n", $order);
end

//[300， +)，优惠100
rule "bookDiscount_4"
    when
        $order:Order(originalPrice >= 300)
    then
        $order.setRealPrice($order.getOriginalPrice() - 100);
        System.out.printf("bookDiscount_4, %s%n", $order);
end