package rules.dateExpires;
global org.slf4j.Logger log
import java.util.Date


dialect  "mvel"


// 1
rule "rule_dateExpires_1"
    // 规则失效时间，格式可以自定义
    date-expires "2020-10-21 11:00:00" // 已过期，不会执行
    when
    then
        log.info("{} - rule_dateExpires_1 occur ", new Date());
end


// 2
rule "rule_dateExpires_2"
    date-expires "2050-10-21 11:00:00" // 未过期，会执行
    when
    then
        log.info("{} - rule_dateExpires_2 occur", new Date());
end

