package rules.global1;

import java.util.Date
import com.corning.drools.service.UserService

global org.slf4j.Logger log
global java.lang.Integer count
global java.util.List gList
global UserService userService // 先 import 可以简化 global 定义

dialect  "mvel"


// 1
rule "rule_global_1"
    when
    then
        log.info("{} rule_global_1 occur", new Date());

        count += 10; // 改变 count 值
        log.info("rule_global_1 count={}", count);

        gList.add("rule_global_1"); // 改变 gList 值
        log.info("rule_global_1 gList.size={}", gList.size());

        userService.save("rule_global_1");
end


// 2
rule "rule_global_2"
    when
    then
        log.info("{} rule_global_2 occur", new Date());
        log.info("rule_global_2 count={}", count);
        log.info("rule_global_2 gList.size={}", gList.size());

        userService.save("rule_global_2");
end

