package rules.lhs;
dialect  "mvel"

import com.corning.drools.entity.Student

global org.slf4j.Logger log


rule "rule_lhs_1"
    when
        $student:Student(age in (1, 3, 5))
    then
        log.info("rule_lhs_1 occur, $student={}", $student);
end

rule "rule_lhs_2"
    when
        $student:Student(age not in (1, 3, 5))
    then
        log.info("rule_lhs_2 occur, $student={}", $student);
end

rule "rule_lhs_eval_1"
    when
        eval(true)
    then
        log.info("rule_lhs_eval_1 occur");
end


rule "rule_lhs_not_1"
    when
        // student age>0 = true, not 取反后为 false， 规则不会执行
        not Student(age > 0)
    then
        log.info("rule_lhs_not_1 occur");
end