package rules.rhs;
dialect  "mvel"

import com.corning.drools.entity.Student
import org.drools.core.WorkingMemory

global org.slf4j.Logger log


rule "rule_rhs_halt_1"
    when
    then
        log.info("rule_rhs_halt_1 occur");
        drools.halt(); // 终止后面所有规则执行
end

rule "rule_rhs_halt_2"
    when
    then
        log.info("rule_rhs_halt_2 occur");
end


rule "rule_rhs_workingMemory_1"
    when
    then
        log.info("rule_rhs_workingMemory_1 occur");
        WorkingMemory workingMemory = drools.getWorkingMemory();
        log.info("workingMemory={}", workingMemory);
end


rule "rule_rhs_getRule_1"
    when
    then
        log.info("rule_rhs_getRule_1 occur");
        org.drools.core.definitions.rule.impl.RuleImpl rule = drools.getRule();
        log.info("rule={}", rule);
        log.info("id={}, autoFocus={}, dateExpires={}", rule.getId(), rule.getAutoFocus(), rule.getDateExpires());
end
