package rules.salience1;
dialect  "mvel"

rule "salience_1"
    salience 1
    when
        eval(true)
    then
        System.out.println("salience_1 occur");
end


rule "salience_2"
    salience 2
    when
        eval(true)
    then
        System.out.println("salience_2 occur");
end


rule "salience_3"
    salience 3
    when
        eval(true)
    then
        System.out.println("salience_3 occur");
end